# Copyright (c) libdragon 2022
# See LICENSE file in the project root for full license information.

# This workflow will build the libdragon N64 GCC toolchain to keep it up-to-date.
name: Build latest libdragon N64 MIPS GCC toolchain

on:
  # This action will take about 50 minutes to run! It is designed to only fire if the GCC toolchain build file changes.
  push:
  pull_request:
  
jobs:
  build-toolchain:
    # targets the oldest ubuntu image available to create valid packages for as many versions possible.
    # TODO: move to using a docker container to support older versions.
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include: [
#          { target-platform: Windows-x86_64, host: x86_64-w64-mingw32 },
          { target-platform: Linux-x86_64, host: '' }
        ]

    steps:
      - name: Install native system build dependencies
        run: |
          sudo apt-get install libmpfr-dev
          sudo apt-get install texinfo
          sudo apt-get install libmpc-dev
          sudo apt-get install squashfs-tools
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      - name: Install x-compile system build dependencies
        if: ${{ matrix.target-platform == 'Windows-x86_64' }}
        run: |
          sudo apt-get install -y mingw-w64
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
      - name: Set up Ruby
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.1'

      - name: Install Package Creator
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        run: |
          echo installing jordansissel/fpm ruby package
          gem install fpm
          fpm --version
        continue-on-error: true

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # we only require the last check-in, unless we want to create a changelog.

      # Cache and restore dependencies instead of downloading them to increase build speed.
      # TODO: will the cache ever expire?!
      # Further research: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ./tools/**/*.tar.gz
            ./tools/**/*.tar.bz2
          key: ${{ runner.os }}-dependency-downloads

      - name: Build N64 MIPS GCC toolchain for ${{ matrix.target-platform }}
        run: |
          # TODO: use runner temp?!
          # required for newlib (as not the default?!)
          export PATH="$PATH:/usr/local/n64-brew"
          cd ./tools/
          sudo N64_INST=/usr/local/n64-brew HOST=${{ matrix.host }} ./build-toolchain.sh
        continue-on-error: true

      - name: Generate debian package
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        run: |
          # https://fpm.readthedocs.io/en/v1.15.0/getting-started.html
          echo generating fpm packages
          fpm \
            -s dir \
            -t deb \
            -p n64brew-libdragon-toolchain-0.0.1-0-any.deb \
            --name n64brew-libdragon-toolchain \
            --license UNLICENSE \
            --version 0.0.1 \
            --architecture all \
            --depends bash \
            --description "libdragon toolchain" \
            --url "https://n64brew.com" \
            --maintainer "N64 Brew Community" \
            n64brew-libdragon-toolchain=/usr/local/n64-brew/ n64brew-libdragon-toolchain.1=/usr/local/n64-brew/.1
        continue-on-error: true

      - name: Publish ${{ matrix.target-platform }} Build Artifacts
        if: ${{ matrix.target-platform == 'Windows-x86_64' }}
        uses: actions/upload-artifact@v3
        with:
          name: gcc-toolchain-mips64-${{ matrix.target-platform }}
          path: |
            /usr/local/n64/n64-brew
        continue-on-error: true

      - name: Publish ${{ matrix.target-platform }} Build Artifacts
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        uses: actions/upload-artifact@v3
        with:
          name: gcc-toolchain-mips64-${{ matrix.target-platform }}
          path: |
            ./**/*.deb
        continue-on-error: true
