# Copyright (c) libdragon 2022
# See LICENSE file in the project root for full license information.

# This workflow will build the libdragon N64 GCC toolchain to keep it up-to-date.
name: Build latest libdragon N64 MIPS GCC toolchain

on:
  # This action will take about 50 minutes to run! It is designed to only fire if the GCC toolchain build file changes.
  push:
  pull_request:
  
jobs:
  build-toolchain:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { target-platform: Linux-x86_64, host: '' }
        ]

    steps:
      - name: Install native system build dependencies
        run: |
          sudo apt-get install libmpfr-dev
          sudo apt-get install texinfo
          sudo apt-get install libmpc-dev
          sudo apt-get install checkinstall
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      - name: Install x-compile system build dependencies
        if: ${{ matrix.target-platform == 'Windows-x86_64' }}
        run: |
          sudo apt-get install -y mingw-w64
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # we only require the last check-in, unless we want to create a changelog.
        

      # Cache and restore dependencies instead of downloading them to increase build speed.
      # TODO: will the cache ever expire?!
      # Further research: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ./tools/**/*.tar.gz
            ./tools/**/*.tar.bz2
          key: ${{ runner.os }}-dependency-downloads

      - name: Build N64 MIPS GCC toolchain for ${{ matrix.target-platform }}
        run: |
          cd ./tools/
          N64_INST=/usr/local/n64-brew/ HOST=${{ matrix.host }} ./build-toolchain.sh


      - name: Publish ${{ matrix.target-platform }} Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gcc-toolchain-mips64-${{ matrix.target-platform }}
          path: |
            /usr/local/n64-brew/**/*.deb
            ./tools/**/*.deb
          #  /usr/local/n64-brew/**/*
