# Copyright (c) libdragon 2022
# See LICENSE file in the project root for full license information.

# This workflow will build the libdragon N64 GCC toolchain to keep it up-to-date.
name: Build latest libdragon N64 MIPS GCC toolchain

on:
  # This action will take about 50 minutes to run! It is designed to only fire if the GCC toolchain build file changes.
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       include: [
         { build: Windows-x86_64, install-location: /usr/local/n64/, host: x86_64-w64-mingw32},
         { build: Linux-x86_64, , install-location: /usr/local/n64/, host: },
         { build: Linux-arm64, , install-location: /usr/local/n64/, host: }
       ]

    steps:

      - name: Install native system build dependencies
        run: |
          sudo apt-get install libmpfr-dev
          sudo apt-get install texinfo
          sudo apt-get install libmpc-dev
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      - name: Install x-compile system build dependencies
        if: ${{ matrix.build == 'Windows-x86_64' }}
        run: |
          sudo apt-get install -y mingw-w64
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      - uses: actions/checkout@v3
        name: Checkout Code

      # Cache and restore dependencies instead of downloading them.
      - uses: actions/cache@v3
        id: cache
        with:
          path: ['**/tar.gz', '**/tar.bz2']
          key: ${{ runner.os }}-downloads

      - name: Build N64 MIPS GCC toolchain for ${{ matrix.build }}
        run: |
          cd ./tools/
          N64_INST=${{ matrix.install-location }} HOST=${{ matrix.host }} ./build-toolchain.sh

      - name: Publish ${{ matrix.build }} Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gcc-toolchain-mips64-${{ matrix.build }}
          path: /usr/local/n64/
